openapi: 3.0.0
info:
  description: |
    Connector Builder Server API

  version: "1.0.0"
  title: Connector Builder Server API
  contact:
    email: contact@airbyte.io
  license:
    name: MIT
    url: "https://opensource.org/licenses/MIT"
externalDocs:
  description: Find out more about Connector Builder
  url: "https://docs.airbyte.com/connector-development/config-based/overview/"

paths:
  /v1/stream/read:
    post:
      summary: Reads a specific stream in the source
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/StreamReadRequestBody"
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StreamRead"
        "400":
          $ref: "#/components/responses/ExceptionResponse"
        "422":
          $ref: "#/components/responses/InvalidInputResponse"
  /v1/streams/list:
    post:
      summary: List all streams present in the connector definition, along with their specific request URLs
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/StreamsListRequestBody"
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StreamsListRead"
        "400":
          $ref: "#/components/responses/ExceptionResponse"
        "422":
          $ref: "#/components/responses/InvalidInputResponse"

components:
  schemas:
    StreamRead:
      type: object
      required:
        - slices
      properties:
        slices:
          type: array
          description: The stream slices returned from the read command
          items:
            type: object
            required:
              - sliceId
              - pages
            properties:
              sliceId:
                type: string
                description: String identifying the current slice
              pages:
                type: array
                description: The pages returned from the read command
                items:
                  type: object
                  required:
                    - pageId
                    - results
                    - logs
                    - request
                    - response
                  properties:
                    pageId:
                      type: string
                      description: String identifying the current page
                    results:
                      type: array
                      description: The RECORD and STATE AirbyteMessages coming from the read operation for this page
                      items:
                        type: string
                    logs:
                      type: array
                      description: The LOG AirbyteMessages coming from the read operation for this page
                      items:
                        type: string
                    request:
                      type: object
                      description: The HTTP request sent to the source API for this page
                      required:
                        - url
                        - headers
                      properties:
                        url:
                          type: string
                          description: URL that the request was sent to
                        body:
                          type: object
                          description: The body of the HTTP request, if present
                        headers:
                          type: object
                          description: The headers of the HTTP request
                    response:
                      type: object
                      description: The response from the source API for this page
                      required:
                        - status
                        - headers
                      properties:
                        status:
                          type: integer
                          description: The status of the response
                        body:
                          type: object
                          description: The body of the HTTP response, if present
                        headers:
                          type: object
                          description: The headers of the HTTP response
    StreamReadRequestBody:
      type: object
      required:
        - definition
        - stream
      properties:
        definition:
          $ref: "#/components/schemas/ConnectorDefinitionBody"
          description: The config-based connector definition contents
        stream:
          type: string
          description: Name of the stream to read
        numSlices:
          type: integer
          description: Number of stream slices to read from the source
          default: 1
        numPages:
          type: integer
          description: Number of pages to read from the source
          default: 1
        state:
          type: object
          description: State blob to use for incremental streams
    ConnectorDefinitionBody:
      $ref: ../../../../airbyte-cdk/python/airbyte_cdk/sources/declarative/config_component_schema.json
    StreamsListRequestBody:
      type: object
      required:
        - definition
      properties:
        definition:
          $ref: "#/components/schemas/ConnectorDefinitionBody"
          description: The config-based connector definition contents
    StreamsListRead:
      type: object
      required:
        - streams
      properties:
        streams:
          type: array
          items:
            type: object
            description: The stream names present in the connector definition
            required:
              - name
              - url
            properties:
              name:
                type: string
                description: The name of the stream
              url:
                type: string
                format: uri
                description: The URL to which read requests will be made for this stream

    # The following exception structs were copied from airbyte-api/src/main/openapi/config.yaml
    InvalidInputProperty:
      type: object
      required:
        - propertyPath
      properties:
        propertyPath:
          type: string
        invalidValue:
          type: string
        message:
          type: string
    KnownExceptionInfo:
      type: object
      required:
        - message
      properties:
        message:
          type: string
        exceptionClassName:
          type: string
        exceptionStack:
          type: array
          items:
            type: string
    InvalidInputExceptionInfo:
      type: object
      required:
        - message
        - validationErrors
      properties:
        message:
          type: string
        exceptionClassName:
          type: string
        exceptionStack:
          type: array
          items:
            type: string
        validationErrors:
          type: array
          items:
            $ref: "#/components/schemas/InvalidInputProperty"

  responses:
    InvalidInputResponse:
      description: Input failed validation
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/InvalidInputExceptionInfo"
    ExceptionResponse:
      description: Exception occurred; see message for details.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/KnownExceptionInfo"
